### PR TITLE
Fix issue when bluetooth off alert didn't show up.

### LINKED ISSUE #262: Show the warning message when Bluetooth is off and user tapping on the "Scan" button
Screenshot at Nov 09 11-42-57

And in the log, it looks like something was found 

Screenshot at Nov 09 11-44-03

### PR DESCRIPTION
**Pull request by Ivan-Skoryk**
## Summary
 
 
Fixes #262
 #### Checklist:
 - [ ] I have added a brief description of the problem in the PR body.
 - [ ] I have explained how I solved the problem in the PR body.
 - [ ] I have covered possible edge cases and side effects.
 - [ ] I have have attached screenshots to the PR of any UI change.
 - [ ] I have checked that my changes work on iOS and macOS targets.
 - [ ] I have checked that my changes work correctly on devices with and without a Home button.
 - [ ] I have added unit tests for the new logic.
 - [ ] I have achieved maximum possible code coverage for the new code.
 - [ ] I have checked that my UI works correctly on both Light and Dark themes.

 #### Acceptance Criteria
 

 #### Screenshots or GIFs (if appropriate)

### CODE REVIEW

File: xDrip/Services/Bluetooth/DexcomG6/DexcomG6BluetoothService.swift [hunk 1]
```diff
@@ -220,6 +220,13 @@ extension DexcomG6BluetoothService: CBCentralManagerDelegate {
         case .resetting, .unknown, .poweredOn, .poweredOff: break
         @unknown default: break
         }
+        
+        if #available(iOS 13, *) {} else {
+            if central.state == .poweredOff {
+                delegate?.serviceDidFail(withError: .bluetoothIsPoweredOff)
+            }
+        }
+
```
Comment (NSFriend) [inline xDrip/Services/Bluetooth/DexcomG6/DexcomG6BluetoothService.swift]: We already have `.poweredOff` case. Could you put this block into?

File: xDrip/Services/Bluetooth/DexcomG6/DexcomG6BluetoothService.swift [hunk 2]
```diff
@@ -217,9 +217,23 @@ extension DexcomG6BluetoothService: CBCentralManagerDelegate {
             
         case .unauthorized: delegate?.serviceDidFail(withError: .bluetoothIsUnauthorized)
         case .unsupported: delegate?.serviceDidFail(withError: .bluetoothUnsupported)
-        case .resetting, .unknown, .poweredOn, .poweredOff: break
```
Comment (NSFriend) [inline xDrip/Services/Bluetooth/DexcomG6/DexcomG6BluetoothService.swift:220]: Remove `.poweredOff` here

File: xDrip/Services/Bluetooth/DexcomG6/DexcomG6BluetoothService.swift [hunk 3]
```diff
@@ -217,9 +217,23 @@ extension DexcomG6BluetoothService: CBCentralManagerDelegate {
...
+        case .resetting, .unknown, .poweredOn: break
         @unknown default: break
         }
+        
+        if #available(iOS 13, *) {} else {
+            if central.state == .poweredOff {
+                delegate?.serviceDidFail(withError: .bluetoothIsPoweredOff)
+            }
+        }
+
```
Comment (NSFriend) [inline xDrip/Services/Bluetooth/DexcomG6/DexcomG6BluetoothService.swift]: Remove this please
