### PR TITLE
Fix issue with left vertical axis numbers on statistics screen. Fix i…

### LINKED ISSUE #115: Show date instead of "00:00" to let user know what day it is on "History" screen graph
For example, like in Nightscout 
Screenshot at Sep 04 18-58-48

### LINKED ISSUE #224: Graphs issues on different screens:
**Rework graphs on all screen:**
 * Use round numbers on "y" axis for mg/dL. 
 * Use the same step on axis. 
 * Add some space above and beyond max and min values, where possible

**Issues:**

1. Numbers are duplicated on "y" axis on "Statistics" screen when mmol/L is selectedI've seen the problem on "TD" and "YTD" tabs

Screenshot at Oct 23 17-01-47

2. Home screen: Graph scale step for all numbers is 2 with equal distances except 3 and 4
Screenshot at Oct 23 17-46-27

3. Home screen: Numbers on the graph can be on the graph edge
Screenshot at Oct 23 18-05-10

### LINKED ISSUE #242: Adjust time on "x" axis on the Main and "History" screens
Time should always be fully displayed with appropriate spaces in-between 

iPhone 7+
Screenshot at Nov 02 16-46-29
Screenshot at Nov 02 16-44-04

iPhone 8
Screenshot at Nov 03 12-05-36

### LINKED ISSUE #277: Low and High ranges in Data table on Main screen are always shown in mg/dL
Screenshot at Nov 26 13-30-34

### PR DESCRIPTION
**Pull request by Ivan-Skoryk**
…ssue with glucose chart date/time labels. Fix issue with wrong values on glucose data view.

## Summary
 
 
Fixes #242 
Fixes #115 
Fixes #224 
Fixes #277

 #### Checklist:
 - [x] I have added a brief description of the problem in the PR body.
 - [x] I have explained how I solved the problem in the PR body.
 - [x] I have covered possible edge cases and side effects.
 - [x] I have have attached screenshots to the PR of any UI change.
 - [x] I have checked that my changes work on iOS and macOS targets.
 - [x] I have checked that my changes work correctly on devices with and without a Home button.
 - [ ] I have added unit tests for the new logic.
 - [ ] I have achieved maximum possible code coverage for the new code.
 - [x] I have checked that my UI works correctly on both Light and Dark themes.

 #### Acceptance Criteria
 

 #### Screenshots or GIFs (if appropriate)
 
image
image
image
image

### CODE REVIEW

File: xDrip/Components/Charts/BaseHistoryView.swift [hunk 1]
```diff
@@ -130,11 +131,18 @@ class BaseHistoryView: UIView {
...
             1.0
         )
-        let chartWidth = scrollContainer.bounds.width * scrollSegments
+        var chartWidth = scrollContainer.bounds.width * scrollSegments
+        #if os(iOS)
+        let width = UIScreen.main.bounds.width
+        if width < 414.0 {
+            multiplier = 1.6 + (414.0 / width) - 1
+        }
+        #endif
```
Comment (Artem-Kalmykov) [inline xDrip/Components/Charts/BaseHistoryView.swift:140]: 😲

**Review by Artem-Kalmykov — APPROVED** [review]
